In [1]:
element = 'oxygen'
print('first three characters', element[0:3])
print('last three characters', element[3:6])

first three characters oxy
last three characters gen


In [2]:
element[:4]

'oxyg'

In [3]:
element[4:]

'en'

In [4]:
element[:]

'oxygen'

1.1)<br>
The value of <code>element[:4]</code> is "oxyg"<br>
The value of <code>element[4:]</code> is "en"<br>
the value of <code>element[:]</code> is "oxygen"

In [5]:
element[-1]

'n'

In [6]:
element[-2]

'e'

1.2)<br>
<code>element[-1]</code> is "n"<br>
<code>element[-2]</code> is "e"

In [7]:
element[1:-1]

'xyge'

1.3)<br>
<code>element[1:-1]</code> prints out the values between <code>element[1]</code> ("n") and <code>element[-1]</code> ("o") to present "xyge".

1.4)<br>
<code>data[3:3,4:4]</code> will produce an empty array as well. The shape will be (0,0) as in zero rows and zero columns.<br>
<code>data[3:3,:]</code> will again produce an empty array. However, the shape of the data will be (0,n) as in zero rows and n number of columns. 

In [9]:
import numpy

A = numpy.array([[1,2,3], [4,5,6], [7, 8, 9]])
print('A = ')
print(A)

B = numpy.hstack([A, A])
print('B = ')
print(B)

C = numpy.vstack([A, A])
print('C = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
#2.1
A2=numpy.delete(A, [2,3], axis=1)
print(A2)

[[1 2]
 [4 5]
 [7 8]]


/home/eebc177student/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  


In [46]:
npdiff = numpy.array([ 0,  2,  5,  9, 14])

In [47]:
numpy.diff(npdiff)

array([2, 3, 4, 5])

3.1)<br>
In the context of patient inflamation data, it would make the most sense to use this function along the x axis (given that each row represents a different patient's individual inflamation records and each column represents each day). By running this function along the x axis, we are able to see the difference in inflamation of each indivual patient each day. 

3.2)<br>
Given that the shape of the dataset is <code>(60,40)</code> (with the same assumptions from the previous answer to 3.1), the resulting shape of the array after running the <code>diff()</code> against the x axis should be <code>(60,39)</code>. The number of rows should not be reduced as the function is not affecting the rows. The number of columns is reduced to 39 from 40 because the values being returned are the differences between consecutive numbers. As there is no proceeding number after the 40th entry, no additional value will be returned. Therefore, there will be 39 returned values.

3.3)<br>
To find the larget change in inflammation for each patient, I would use the <code>max()</code> and <code>abs()</code> function on the x axis. It will not matter whether the change in inflammation is an increase or decrease since we are looking at the absolute value of the change.<br>
<br>
For example using this theoretical dataset:<br>
<code>import numpy</code><br>
<code>data = numpy.loadtxt(fname='data.csv', delimiter=",")</code><br>
<code>patient1 = data[0,:]</code><br>
<code>maxp1 = max(abs(diff(patient1)))</code><br>
And repeat for each patient