In [3]:
3+5*4

23

In [4]:
weight_kg = 60

In [5]:
weight_kg

60

In [7]:
weight_kg_text = "weight in kilograms:"

In [8]:
print(weight_kg_text,weight_kg)

weight in kilograms: 60


In [9]:
print('weight in pounds:',weight_kg*2.2)

weight in pounds: 132.0


In [10]:
print(weight_kg)

60


In [11]:
print(weight_kg)
weight_kg = 230

60


In [12]:
print(weight_kg)

230


In [13]:
print(weight_kg)
weight_kg = weight_kg*3
print(weight_kg)

230
690


In [14]:
print(weight_kg)
weight_kg = weight_kg*3
print(weight_kg)

690
2070


In [15]:
x = 5
y = 6
print(x+y)

11


In [16]:
x = 5
y = 6
print(x+y)
x = y
print(x+y)

11
12


In [17]:
x = 5
y = 6
print(x+y)
x = y
print(x+y)

11
12


In [18]:
mass = 47.5
age = 122
mass = mass * 5.0
age = age - 10
print(mass,age)

237.5 112


In [19]:
first, second = 'grace', 'shawn'

In [25]:
import numpy

numpy.loadtxt(fname='inflammation-01.csv', delimiter=",")

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.]])

In [26]:
medicaldata=numpy.loadtxt(fname='inflammation-01.csv', delimiter=",")

In [27]:
medicaldata

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.]])

In [28]:
print(type(medicaldata))

<class 'numpy.ndarray'>


In [29]:
print(medicaldata.dtype)

float64


In [31]:
medicaldata.shape #rows, then columns

(54, 40)

In [32]:
colors = ['red','green','blue']

In [33]:
colors[0]

'red'

In [36]:
print('first value in medical data:',medicaldata[0,0])

first value in medical data: 0.0


In [37]:
print('first value in medical data:',medicaldata[30,20])

first value in medical data: 6.0


In [38]:
medicaldata.shape

(54, 40)

In [39]:
medshape=medicaldata.shape

In [40]:
medshape

(54, 40)

In [41]:
middlerow=medshape[0]/2
middlecol=medshape[1]/2

In [43]:
(middlerow,middlecol)

(27.0, 20.0)

In [45]:
middlerow=int(medshape[0]/2)
middlecol=int(medshape[1]/2)

In [46]:
## slicing data
print(medicaldata[0:4,0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [47]:
print(medicaldata[5:10,0:10])

[[0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [55]:
bruin = medicaldata[:,36:]
print('bruin is:\n')
print(bruin)

bruin is:

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]
 [2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [54]:
import numpy as np

In [56]:
import time

In [57]:
print(time.ctime())

Mon Jan 27 12:20:43 2020


In [58]:
meanval, stdval = np.mean(medicaldata), np.std(medicaldata)

In [59]:
stdval

4.352194529455482

In [60]:
maxval, minval = np.max(medicaldata), np.min(medicaldata)

In [61]:
maxval
minval

0.0

In [62]:
maxval

19.0

In [63]:
len(medicaldata)

54

In [69]:
patient1=medicaldata[0,:]
patient1

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [70]:
len(patient1)

40

In [71]:
patient1[1]

0.0

In [72]:
max(patient1)

18.0

In [73]:
maxp1=max(patient1)

In [75]:
maxp1

18.0

In [76]:
print(np.max(medicaldata, axis=1))

[18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19.
 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19.
 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19. 18. 18. 19.]


In [77]:
print(np.max(medicaldata, axis=0))

[ 0.  1.  2.  3.  3.  2.  6.  7.  8.  9. 10. 11. 10.  9.  7. 15.  7. 16.
 12. 18. 19. 14. 12. 17. 12. 12. 11.  7. 11.  8. 10.  5.  5.  7.  5.  5.
  2.  3.  1.  1.]


In [88]:
def helloperson(name="shawn", friend="tom"):
    print("hello", name, "and your friend", friend, "too!")

In [90]:
helloperson("alton")

hello alton and your friend tom too!


In [92]:
helloperson(friend="mike", name="kris")

hello kris and your friend mike too!


In [98]:
def squarenum(x):
    square=x*x
    return(square)

In [99]:
print(squarenum(9))

81


In [100]:
def squarenum(x):
    return(x*x)

In [103]:
squarenum(92)

8464

In [104]:
5^3

6

In [105]:
5**3

125

In [109]:
def pw(x,y):
    return(x**y)

In [110]:
pw(5,6)

15625