In [15]:
def f2c(t):
    return((t-32)*(5/9))

In [19]:
def c2k(t):
    return(t+273.15)

In [26]:
def f2k(t):
    x = f2c(t)
    y = c2k(x)
    return(y)

In [35]:
def f2k2(t):
    return(c2k(f2c(t)))

# Functions

In [2]:
# end goal: visualize file ('file.csv', ';')
# goal: create a function that will do the following steps:
# 1) read in the data file
# 2) create our 3 subplot holders with the empty figure
# 3) plot each of them
# 4) we want to show the plot

def visualize(filename, delim = ','):
    data = numpy.loadtxt(fname = filename, delimiter = 'delim') #1
    
    fig = matplotlib.pyplot.figure(figsize = (10.0, 3.0)) #2
    axes1 = fig.add_subplot(1, 3, 1)
    axes2 = fig.add_subplot(1, 3, 2)
    axes3 = fig.add_subplot(1, 3, 3)
    
    axes1.set_ylabel('average') #3
    axes1.plot(numpy.mean(data, axes = 0))
    axes2.set_ylabel('max')
    axes2.plot(numpy.max(data, axes = 0))
    axes3.set_ylabel('min')
    axes3.plot(numpy.min(data, axes = 0))
    
    fig.tight_layout() #4
    matplotlib.pyplot.show()

In [3]:
import numpy
import matplotlib.pyplot

In [4]:
visualize('inflammation-01.csv', ',')

ValueError: could not convert string to float: '0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0'

In [50]:
import glob
filenames = sorted(glob.glob('inflammation*.csv'))

In [52]:
# lets create a for loop that would run through the entire filelist
# and will plot the 3 panel figure for each inflammation data file

for files in filenames:
    print(files)
    visualize(files)

inflammation-01.csv


ValueError: could not convert string to float: '0,0,1,3,1,2,4,7,8,3,3,3,10,5,7,4,7,7,12,18,6,13,11,11,7,7,4,6,8,8,4,4,5,7,3,4,2,3,0,0'

# Testing, Debugging, and Documenting Functions

In [68]:
def offset_mean(data, target_mean_value):
    '''return a new array containing the original data with its
    mean offset to match the desired value, (0 by defaut)
    
    ----------
    @param data an n- dimensional array of values
    @param target_mean_value the value you want to offset by (0 by default
    @return a new array containing the original data with
    its mean offset to match the desired value
    
    Examples
    ----------
    >>> offset_mean([1, 2, 3]))
    array([-1., 0., 1.])
    
    '''
    return(data - numpy.mean(data) + target_mean_value)







In [58]:
z = numpy.zeros((2,2))

In [60]:
print(z)

[[0. 0.]
 [0. 0.]]


In [62]:
print(offset_mean(z,3))

[[3. 3.]
 [3. 3.]]


In [65]:
data = numpy.loadtxt(fname = 'inflammation-01.csv', delimiter = ',')
offset_inflammation = offset_mean(data, 12)
print(offset_inflammation)

[[6.34166667 6.34166667 7.34166667 ... 9.34166667 6.34166667 6.34166667]
 [6.34166667 7.34166667 8.34166667 ... 7.34166667 6.34166667 7.34166667]
 [6.34166667 7.34166667 7.34166667 ... 8.34166667 7.34166667 7.34166667]
 ...
 [6.34166667 6.34166667 7.34166667 ... 9.34166667 6.34166667 6.34166667]
 [6.34166667 7.34166667 8.34166667 ... 7.34166667 6.34166667 7.34166667]
 [6.34166667 7.34166667 7.34166667 ... 8.34166667 7.34166667 7.34166667]]


In [67]:
print('std before and after offset:', numpy.std(data), numpy.std(offset_inflammation) )

std before and after offset: 4.352194529455482 4.352194529455482


In [69]:
help(offset_mean)

Help on function offset_mean in module __main__:

offset_mean(data, target_mean_value)
    return a new array containing the original data with its
    mean offset to match the desired value, (0 by defaut)
    
    ----------
    @param data an n- dimensional array of values
    @param target_mean_value the value you want to offset by (0 by default
    @return a new array containing the original data with
    its mean offset to match the desired value
    
    Examples
    ----------
    >>> offset_mean([1, 2, 3]))
    array([-1., 0., 1.])

